-- Insert data into Departments
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Computer Science', 'CS101', 'Tech Building', 'T101', '+12025550123', 'cs@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Mathematics', 'MATH102', 'Science Hall', 'S201', '+12025550124', 'math@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Physics', 'PHY103', 'Science Hall', 'S301', '+12025550125', 'physics@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Chemistry', 'CHEM104', 'Lab Building', 'L401', '+12025550126', 'chem@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Biology', 'BIO105', 'Lab Building', 'L501', '+12025550127', 'bio@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('English', 'ENG106', 'Arts Building', 'A601', '+12025550128', 'english@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('History', 'HIST107', 'Arts Building', 'A701', '+12025550129', 'history@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Economics', 'ECON108', 'Business School', 'B801', '+12025550130', 'econ@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Business Administration', 'BA109', 'Business School', 'B901', '+12025550131', 'ba@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Psychology', 'PSY110', 'Social Sciences', 'SS101', '+12025550132', 'psych@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Sociology', 'SOC111', 'Social Sciences', 'SS201', '+12025550133', 'soc@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Political Science', 'POL112', 'Social Sciences', 'SS301', '+12025550134', 'polsci@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Engineering', 'ENG113', 'Tech Building', 'T201', '+12025550135', 'eng@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Mechanical Engineering', 'ME114', 'Tech Building', 'T301', '+12025550136', 'me@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Electrical Engineering', 'EE115', 'Tech Building', 'T401', '+12025550137', 'ee@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Civil Engineering', 'CE116', 'Tech Building', 'T501', '+12025550138', 'ce@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Art', 'ART117', 'Arts Building', 'A801', '+12025550139', 'art@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Music', 'MUS118', 'Arts Building', 'A901', '+12025550140', 'music@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Philosophy', 'PHIL119', 'Arts Building', 'A1001', '+12025550141', 'phil@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Anthropology', 'ANTH120', 'Social Sciences', 'SS401', '+12025550142', 'anth@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Geography', 'GEO121', 'Science Hall', 'S401', '+12025550143', 'geo@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Statistics', 'STAT122', 'Science Hall', 'S501', '+12025550144', 'stat@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Environmental Science', 'ENV123', 'Lab Building', 'L601', '+12025550145', 'env@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Education', 'EDU124', 'Education Building', 'E101', '+12025550146', 'edu@university.edu');
INSERT INTO Departments (DepartmentName, DepartmentCode, Building, OfficeNumber, Phone, Email) VALUES ('Nursing', 'NUR125', 'Health Sciences', 'H101', '+12025550147', 'nur@university.edu');

-- Insert data into Faculty
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('John', 'Smith', 1, 'john.smith@university.edu', '+12025550148', TO_DATE('2010-08-15', 'YYYY-MM-DD'), 'Professor', 'T102', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Alice', 'Johnson', 1, 'alice.johnson@university.edu', '+12025550149', TO_DATE('2012-09-01', 'YYYY-MM-DD'), 'Associate Professor', 'T103', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Robert', 'Brown', 2, 'robert.brown@university.edu', '+12025550150', TO_DATE('2008-07-10', 'YYYY-MM-DD'), 'Professor', 'S202', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Emma', 'Davis', 2, 'emma.davis@university.edu', '+12025550151', TO_DATE('2015-08-20', 'YYYY-MM-DD'), 'Assistant Professor', 'S203', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Michael', 'Wilson', 3, 'michael.wilson@university.edu', '+12025550152', TO_DATE('2011-09-05', 'YYYY-MM-DD'), 'Professor', 'S302', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Sarah', 'Taylor', 3, 'sarah.taylor@university.edu', '+12025550153', TO_DATE('2016-08-15', 'YYYY-MM-DD'), 'Lecturer', 'S303', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('David', 'Martinez', 4, 'david.martinez@university.edu', '+12025550154', TO_DATE('2009-07-01', 'YYYY-MM-DD'), 'Associate Professor', 'L402', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Laura', 'Garcia', 4, 'laura.garcia@university.edu', '+12025550155', TO_DATE('2014-08-10', 'YYYY-MM-DD'), 'Assistant Professor', 'L403', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('James', 'Rodriguez', 5, 'james.rodriguez@university.edu', '+12025550156', TO_DATE('2013-09-01', 'YYYY-MM-DD'), 'Professor', 'L502', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Emily', 'Hernandez', 5, 'emily.hernandez@university.edu', '+12025550157', TO_DATE('2017-08-20', 'YYYY-MM-DD'), 'Lecturer', 'L503', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('William', 'Lopez', 6, 'william.lopez@university.edu', '+12025550158', TO_DATE('2010-08-01', 'YYYY-MM-DD'), 'Professor', 'A602', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Sophia', 'Gonzalez', 6, 'sophia.gonzalez@university.edu', '+12025550159', TO_DATE('2015-09-10', 'YYYY-MM-DD'), 'Associate Professor', 'A603', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Daniel', 'Perez', 7, 'daniel.perez@university.edu', '+12025550160', TO_DATE('2012-07-15', 'YYYY-MM-DD'), 'Assistant Professor', 'A702', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Olivia', 'Sanchez', 7, 'olivia.sanchez@university.edu', '+12025550161', TO_DATE('2016-08-05', 'YYYY-MM-DD'), 'Lecturer', 'A703', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Thomas', 'Ramirez', 8, 'thomas.ramirez@university.edu', '+12025550162', TO_DATE('2009-09-01', 'YYYY-MM-DD'), 'Professor', 'B802', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Isabella', 'Torres', 8, 'isabella.torres@university.edu', '+12025550163', TO_DATE('2014-08-15', 'YYYY-MM-DD'), 'Associate Professor', 'B803', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Charles', 'Flores', 9, 'charles.flores@university.edu', '+12025550164', TO_DATE('2011-07-10', 'YYYY-MM-DD'), 'Assistant Professor', 'B902', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Mia', 'Rivera', 9, 'mia.rivera@university.edu', '+12025550165', TO_DATE('2017-09-01', 'YYYY-MM-DD'), 'Lecturer', 'B903', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Joseph', 'Gomez', 10, 'joseph.gomez@university.edu', '+12025550166', TO_DATE('2013-08-20', 'YYYY-MM-DD'), 'Professor', 'SS102', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Ava', 'Diaz', 10, 'ava.diaz@university.edu', '+12025550167', TO_DATE('2016-08-10', 'YYYY-MM-DD'), 'Associate Professor', 'SS103', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Matthew', 'Reyes', 11, 'matthew.reyes@university.edu', '+12025550168', TO_DATE('2010-09-05', 'YYYY-MM-DD'), 'Assistant Professor', 'SS202', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Charlotte', 'Cruz', 11, 'charlotte.cruz@university.edu', '+12025550169', TO_DATE('2015-08-15', 'YYYY-MM-DD'), 'Lecturer', 'SS203', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Andrew', 'Ortiz', 12, 'andrew.ortiz@university.edu', '+12025550170', TO_DATE('2012-07-01', 'YYYY-MM-DD'), 'Professor', 'SS302', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Amelia', 'Morales', 12, 'amelia.morales@university.edu', '+12025550171', TO_DATE('2017-09-10', 'YYYY-MM-DD'), 'Associate Professor', 'SS303', 'Active');
INSERT INTO Faculty (FirstName, LastName, DepartmentID, Email, Phone, HireDate, Rank, OfficeLocation, Status) VALUES ('Steven', 'Nguyen', 13, 'steven.nguyen@university.edu', '+12025550172', TO_DATE('2011-08-01', 'YYYY-MM-DD'), 'Assistant Professor', 'T202', 'Active');

-- Update Departments with HeadFacultyID
UPDATE Departments SET HeadFacultyID = 1 WHERE DepartmentID = 1;
UPDATE Departments SET HeadFacultyID = 3 WHERE DepartmentID = 2;
UPDATE Departments SET HeadFacultyID = 5 WHERE DepartmentID = 3;
UPDATE Departments SET HeadFacultyID = 7 WHERE DepartmentID = 4;
UPDATE Departments SET HeadFacultyID = 9 WHERE DepartmentID = 5;
UPDATE Departments SET HeadFacultyID = 11 WHERE DepartmentID = 6;
UPDATE Departments SET HeadFacultyID = 13 WHERE DepartmentID = 7;
UPDATE Departments SET HeadFacultyID = 15 WHERE DepartmentID = 8;
UPDATE Departments SET HeadFacultyID = 17 WHERE DepartmentID = 9;
UPDATE Departments SET HeadFacultyID = 19 WHERE DepartmentID = 10;
UPDATE Departments SET HeadFacultyID = 21 WHERE DepartmentID = 11;
UPDATE Departments SET HeadFacultyID = 23 WHERE DepartmentID = 12;
UPDATE Departments SET HeadFacultyID = 25 WHERE DepartmentID = 13;

-- Insert data into Students
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Liam', 'Anderson', 'liam.anderson@university.edu', '+12025550173', TO_DATE('2000-05-15', 'YYYY-MM-DD'), TO_DATE('2022-09-01', 'YYYY-MM-DD'), 1, 'B.Sc. Computer Science', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Noah', 'Thomas', 'noah.thomas@university.edu', '+12025550174', TO_DATE('2001-06-20', 'YYYY-MM-DD'), TO_DATE('2022-09-01', 'YYYY-MM-DD'), 1, 'B.Sc. Computer Science', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Oliver', 'Jackson', 'oliver.jackson@university.edu', '+12025550175', TO_DATE('1999-07-10', 'YYYY-MM-DD'), TO_DATE('2021-09-01', 'YYYY-MM-DD'), 2, 'B.Sc. Mathematics', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Elijah', 'White', 'elijah.white@university.edu', '+12025550176', TO_DATE('2000-08-25', 'YYYY-MM-DD'), TO_DATE('2021-09-01', 'YYYY-MM-DD'), 2, 'B.Sc. Mathematics', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('James', 'Harris', 'james.harris@university.edu', '+12025550177', TO_DATE('2002-09-15', 'YYYY-MM-DD'), TO_DATE('2023-09-01', 'YYYY-MM-DD'), 3, 'B.Sc. Physics', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('William', 'Lewis', 'william.lewis@university.edu', '+12025550178', TO_DATE('2001-10-05', 'YYYY-MM-DD'), TO_DATE('2022-09-01', 'YYYY-MM-DD'), 3, 'B.Sc. Physics', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Benjamin', 'Walker', 'benjamin.walker@university.edu', '+12025550179', TO_DATE('2000-11-20', 'YYYY-MM-DD'), TO_DATE('2021-09-01', 'YYYY-MM-DD'), 4, 'B.Sc. Chemistry', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Lucas', 'Hall', 'lucas.hall@university.edu', '+12025550180', TO_DATE('2002-12-10', 'YYYY-MM-DD'), TO_DATE('2023-09-01', 'YYYY-MM-DD'), 4, 'B.Sc. Chemistry', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Henry', 'Allen', 'henry.allen@university.edu', '+12025550181', TO_DATE('2001-01-15', 'YYYY-MM-DD'), TO_DATE('2022-09-01', 'YYYY-MM-DD'), 5, 'B.Sc. Biology', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Alexander', 'Young', 'alexander.young@university.edu', '+12025550182', TO_DATE('2000-02-25', 'YYYY-MM-DD'), TO_DATE('2021-09-01', 'YYYY-MM-DD'), 5, 'B.Sc. Biology', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Emma', 'King', 'emma.king@university.edu', '+12025550183', TO_DATE('2002-03-10', 'YYYY-MM-DD'), TO_DATE('2023-09-01', 'YYYY-MM-DD'), 6, 'B.A. English', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Ava', 'Wright', 'ava.wright@university.edu', '+12025550184', TO_DATE('2001-04-20', 'YYYY-MM-DD'), TO_DATE('2022-09-01', 'YYYY-MM-DD'), 6, 'B.A. English', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Sophia', 'Scott', 'sophia.scott@university.edu', '+12025550185', TO_DATE('2000-05-15', 'YYYY-MM-DD'), TO_DATE('2021-09-01', 'YYYY-MM-DD'), 7, 'B.A. History', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Charlotte', 'Green', 'charlotte.green@university.edu', '+12025550186', TO_DATE('2002-06-25', 'YYYY-MM-DD'), TO_DATE('2023-09-01', 'YYYY-MM-DD'), 7, 'B.A. History', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Mia', 'Adams', 'mia.adams@university.edu', '+12025550187', TO_DATE('2001-07-10', 'YYYY-MM-DD'), TO_DATE('2022-09-01', 'YYYY-MM-DD'), 8, 'B.Sc. Economics', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Amelia', 'Baker', 'amelia.baker@university.edu', '+12025550188', TO_DATE('2000-08-20', 'YYYY-MM-DD'), TO_DATE('2021-09-01', 'YYYY-MM-DD'), 8, 'B.Sc. Economics', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Harper', 'Nelson', 'harper.nelson@university.edu', '+12025550189', TO_DATE('2002-09-15', 'YYYY-MM-DD'), TO_DATE('2023-09-01', 'YYYY-MM-DD'), 9, 'B.B.A.', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Evelyn', 'Carter', 'evelyn.carter@university.edu', '+12025550190', TO_DATE('2001-10-05', 'YYYY-MM-DD'), TO_DATE('2022-09-01', 'YYYY-MM-DD'), 9, 'B.B.A.', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Abigail', 'Mitchell', 'abigail.mitchell@university.edu', '+12025550191', TO_DATE('2000-11-20', 'YYYY-MM-DD'), TO_DATE('2021-09-01', 'YYYY-MM-DD'), 10, 'B.Sc. Psychology', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Emily', 'Perez', 'emily.perez@university.edu', '+12025550192', TO_DATE('2002-12-10', 'YYYY-MM-DD'), TO_DATE('2023-09-01', 'YYYY-MM-DD'), 10, 'B.Sc. Psychology', 'Active');
INSERT INTO Students (FirstName, LastName, Emailivism, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Elizabeth', 'Roberts', 'elizabeth.roberts@university.edu', '+12025550193', TO_DATE('2001-01-15', 'YYYY-MM-DD'), TO_DATE('2022-09-01', 'YYYY-MM-DD'), 11, 'B.A. Sociology', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Sofia', 'Turner', 'sofia.turner@university.edu', '+12025550194', TO_DATE('2000-02-25', 'YYYY-MM-DD'), TO_DATE('2021-09-01', 'YYYY-MM-DD'), 11, 'B.A. Sociology', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Avery', 'Phillips', 'avery.phillips@university.edu', '+12025550195', TO_DATE('2002-03-10', 'YYYY-MM-DD'), TO_DATE('2023-09-01', 'YYYY-MM-DD'), 12, 'B.A. Political Science', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Mila', 'Campbell', 'mila.campbell@university.edu', '+12025550196', TO_DATE('2001-04-20', 'YYYY-MM-DD'), TO_DATE('2022-09-01', 'YYYY-MM-DD'), 12, 'B.A. Political Science', 'Active');
INSERT INTO Students (FirstName, LastName, Email, Phone, DateOfBirth, AdmissionDate, DepartmentID, Program, Status) VALUES ('Scarlett', 'Parker', 'scarlett.parker@university.edu', '+12025550197', TO_DATE('2000-05-15', 'YYYY-MM-DD'), TO_DATE('2021-09-01', 'YYYY-MM-DD'), 13, 'B.Sc. Engineering', 'Active');

-- Insert data into Courses
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('CSC101', 'Introduction to Programming', 1, 3, 'Undergraduate', 'Basics of programming in Python', NULL, 100);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('CSC201', 'Data Structures', 1, 3, 'Undergraduate', 'Advanced data structures', 'CSC101', 80);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('CSC301', 'Algorithms', 1, 3, 'Undergraduate', 'Algorithm design and analysis', 'CSC201', 60);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('MATH101', 'Calculus I', 2, 4, 'Undergraduate', 'Limits, derivatives, integrals', NULL, 120);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('MATH201', 'Calculus II', 2, 4, 'Undergraduate', 'Advanced integration', 'MATH101', 100);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('MATH301', 'Linear Algebra', 2, 3, 'Undergraduate', 'Matrices and vector spaces', 'MATH101', 80);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('PHY101', 'Mechanics', 3, 4, 'Undergraduate', 'Newtonian mechanics', NULL, 90);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('PHY201', 'Electromagnetism', 3, 4, 'Undergraduate', 'Electric and magnetic fields', 'PHY101', 70);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('CHEM101', 'General Chemistry', 4, 4, 'Undergraduate', 'Basic chemical principles', NULL, 100);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('CHEM201', 'Organic Chemistry', 4, 4, 'Undergraduate', 'Organic compounds', 'CHEM101', 80);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('BIO101', 'Introduction to Biology', 5, 3, 'Undergraduate', 'Cell biology and genetics', NULL, 100);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('BIO201', 'Ecology', 5, 3, 'Undergraduate', 'Ecosystems and biodiversity', 'BIO101', 70);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('ENG101', 'English Composition', 6, 3, 'Undergraduate', 'Writing skills', NULL, 50);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('ENG201', 'British Literature', 6, 3, 'Undergraduate', 'Study of British authors', 'ENG101', 40);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('HIST101', 'World History', 7, 3, 'Undergraduate', 'Global historical events', NULL, 60);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('HIST201', 'American History', 7, 3, 'Undergraduate', 'US history from 1607', 'HIST101', 50);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('ECON101', 'Microeconomics', 8, 3, 'Undergraduate', 'Supply and demand', NULL, 80);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('ECON201', 'Macroeconomics', 8, 3, 'Undergraduate', 'National economies', 'ECON101', 70);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('BA101', 'Introduction to Business', 9, 3, 'Undergraduate', 'Business fundamentals', NULL, 100);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('BA201', 'Marketing', 9, 3, 'Undergraduate', 'Marketing strategies', 'BA101', 80);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('PSY101', 'Introduction to Psychology', 10, 3, 'Undergraduate', 'Human behavior', NULL, 90);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('PSY201', 'Cognitive Psychology', 10, 3, 'Undergraduate', 'Mental processes', 'PSY101', 70);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('SOC101', 'Introduction to Sociology', 11, 3, 'Undergraduate', 'Social structures', NULL, 80);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('SOC201', 'Social Theory', 11, 3, 'Undergraduate', 'Sociological theories', 'SOC101', 60);
INSERT INTO Courses (CourseCode, CourseName, DepartmentID, Credits, Level, Description, Prerequisites, MaxEnrollment) VALUES ('POL101', 'Introduction to Political Science', 12, 3, 'Undergraduate', 'Political systems', NULL, 70);

-- Insert data into Classrooms
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Tech Building', 'T101', 50, 'Projector, Whiteboard');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Tech Building', 'T102', 40, 'Projector, Computers');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Tech Building', 'T103', 60, 'Whiteboard, Lab Equipment');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Science Hall', 'S201', 70, 'Projector, Whiteboard');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Science Hall', 'S202', 50, 'Lab Equipment');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Science Hall', 'S203', 80, 'Projector, Whiteboard');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Lab Building', 'L401', 40, 'Lab Equipment, Whiteboard');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Lab Building', 'L402', 50, 'Projector, Lab Equipment');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Lab Building', 'L403', 60, 'Whiteboard, Computers');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Arts Building', 'A601', 30, 'Projector, Whiteboard');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Arts Building', 'A602', 40, 'Whiteboard');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Arts Building', 'A603', 50, 'Projector, Whiteboard');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Business School', 'B801', 60, 'Projector, Computers');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Business School', 'B802', 70, 'Whiteboard, Projector');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Business School', 'B803', 80, 'Projector, Whiteboard');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Social Sciences', 'SS101', 50, 'Whiteboard, Projector');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Social Sciences', 'SS102', 40, 'Projector, Whiteboard');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Social Sciences', 'SS103', 60, 'Whiteboard, Computers');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Tech Building', 'T201', 70, 'Projector, Lab Equipment');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Tech Building', 'T202', 50, 'Whiteboard, Projector');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Science Hall', 'S301', 80, 'Lab Equipment, Projector');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Science Hall', 'S302', 40, 'Whiteboard, Projector');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Lab Building', 'L501', 60, 'Lab Equipment, Whiteboard');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Lab Building', 'L502', 50, 'Projector, Whiteboard');
INSERT INTO Classrooms (Building, RoomNumber, Capacity, Facilities) VALUES ('Arts Building', 'A701', 70, 'Whiteboard, Projector');

-- Insert data into CourseOfferings
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (1, 1, 'Fall', 2024, 'MWF 09:00-10:00', 1, 30, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (1, 2, 'Spring', 2025, 'TTh 10:30-12:00', 2, 25, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (2, 1, 'Spring', 2025, 'MWF 10:00-11:00', 3, 20, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (3, 2, 'Fall', 2024, 'TTh 13:00-14:30', 1, 15, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (4, 3, 'Fall', 2024, 'MWF 08:00-09:20', 4, 40, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (4, 4, 'Spring', 2025, 'TTh 09:00-10:30', 5, 35, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (5, 3, 'Spring', 2025, 'MWF 11:00-12:20', 6, 30, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (6, 4, 'Fall', 2024, 'TTh 14:00-15:30', 4, 25, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (7, 5, 'Fall', 2024, 'MWF 09:00-10:20', 7, 35, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (8, 6, 'Spring', 2025, 'TTh 10:00-11:30', 8, 30, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (9, 7, 'Fall', 2024, 'MWF 10:00-11:20', 9, 40, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (10, 8, 'Spring', 2025, 'TTh 11:00-12:30', 10, 35, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (11, 9, 'Fall', 2024, 'MWF 08:00-09:00', 11, 30, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (12, 10, 'Spring', 2025, 'TTh 09:00-10:30', 12, 25, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (13, 11, 'Fall', 2024, 'MWF 11:00-12:00', 13, 20, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (14, 12, 'Spring', 2025, 'TTh 13:00-14:30', 14, 15, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (15, 13, 'Fall', 2024, 'MWF 09:00-10:00', 15, 25, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (16, 14, 'Spring', 2025, 'TTh 10:00-11:30', 16, 20, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (17, 15, 'Fall', 2024, 'MWF 10:00-11:00', 17, 30, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (18, 16, 'Spring', 2025, 'TTh 11:00-12:30', 18, 25, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (19, 17, 'Fall', 2024, 'MWF 08:00-09:00', 19, 35, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (20, 18, 'Spring', 2025, 'TTh 09:00-10:30', 20, 30, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (21, 19, 'Fall', 2024, 'MWF 11:00-12:00', 21, 25, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (22, 20, 'Spring', 2025, 'TTh 13:00-14:30', 22, 20, 'Open');
INSERT INTO CourseOfferings (CourseID, FacultyID, Semester, AcademicYear, Schedule, ClassroomID, CurrentEnrollment, Status) VALUES (23, 21, 'Fall', 2024, 'MWF 09:00-10:00', 23, 30, 'Open');

-- Insert data into Enrollments
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (1, 1, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (2, 1, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (1, 2, TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (2, 2, TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (3, 5, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (4, 5, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (3, 6, TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (4, 6, TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (5, 9, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (6, 9, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (5, 10, TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (6, 10, TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (7, 11, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (8, 11, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (7, 12, TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (8, 12, TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (9, 13, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (10, 13, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (9, 14, TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (10, 14, TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (11, 15, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (12, 15, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (11, 16, TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (12, 16, TO_DATE('2025-01-10', 'YYYY-MM-DD'), NULL, 'Enrolled');
INSERT INTO Enrollments (StudentID, OfferingID, EnrollmentDate, Grade, Status) VALUES (13, 17, TO_DATE('2024-08-15', 'YYYY-MM-DD'), NULL, 'Enrolled');

-- Insert data into CoursePrerequisites
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (2, 1);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (3, 2);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (5, 4);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (6, 4);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (8, 7);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (10, 9);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (12, 11);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (14, 13);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (16, 15);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (18, 17);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (20, 19);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (22, 21);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (24, 23);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (3, 1);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (5, 1);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (6, 5);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (8, 4);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (10, 7);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (12, 9);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (14, 11);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (16, 13);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (18, 15);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (20, 17);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (22, 19);
INSERT INTO CoursePrerequisites (CourseID, PrerequisiteCourseID) VALUES (24, 21);

-- Insert data into Transcripts
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (1, 1, 'Spring', 2024, 'A', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (2, 1, 'Spring', 2024, 'B+', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (3, 4, 'Spring', 2024, 'A-', 4);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (4, 4, 'Spring', 2024, 'B', 4);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (5, 7, 'Spring', 2024, 'A', 4);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (6, 7, 'Spring', 2024, 'B+', 4);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (7, 9, 'Spring', 2024, 'A-', 4);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (8, 9, 'Spring', 2024, 'B', 4);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (9, 11, 'Spring', 2024, 'A', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (10, 11, 'Spring', 2024, 'B+', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (11, 13, 'Spring', 2024, 'A-', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (12, 13, 'Spring', 2024, 'B', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (13, 15, 'Spring', 2024, 'A', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (14, 15, 'Spring', 2024, 'B+', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (15, 17, 'Spring', 2024, 'A-', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (16, 17, 'Spring', 2024, 'B', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (17, 19, 'Spring', 2024, 'A', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (18, 19, 'Spring', 2024, 'B+', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (19, 21, 'Spring', 2024, 'A-', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (20, 21, 'Spring', 2024, 'B', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (21, 23, 'Spring', 2024, 'A', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (22, 23, 'Spring', 2024, 'B+', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (23, 1, 'Spring', 2024, 'A-', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (24, 1, 'Spring', 2024, 'B', 3);
INSERT INTO Transcripts (StudentID, CourseID, Semester, AcademicYear, Grade, CreditsEarned) VALUES (25, 4, 'Spring', 2024, 'A', 4);

-- Insert data into FacultyCourseAssignments
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (1, 1);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (1, 2);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (2, 1);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (2, 3);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (3, 4);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (3, 5);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (4, 4);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (4, 6);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (5, 7);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (6, 8);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (7, 9);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (8, 10);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (9, 11);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (10, 12);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (11, 13);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (12, 14);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (13, 15);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (14, 16);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (15, 17);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (16, 18);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (17, 19);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (18, 20);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (19, 21);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (20, 22);
INSERT INTO FacultyCourseAssignments (FacultyID, CourseID) VALUES (21, 23);

-- Commit the changes
COMMIT;